INSERT INTO permissions (id, resource, action)
VALUES
  (gen_random_uuid(), 'orders', 'read'),
  (gen_random_uuid(), 'orders', 'write'),
  (gen_random_uuid(), 'orders', 'delete'),
  (gen_random_uuid(), 'products', 'read'),
  (gen_random_uuid(), 'products', 'write'),
  (gen_random_uuid(), 'products', 'delete'),
  (gen_random_uuid(), 'customers', 'read'),
  (gen_random_uuid(), 'customers', 'write'),
  (gen_random_uuid(), 'customers', 'delete'),
  (gen_random_uuid(), 'inventory', 'read'),
  (gen_random_uuid(), 'inventory', 'write'),
  (gen_random_uuid(), 'inventory', 'delete'),
  (gen_random_uuid(), 'analytics', 'read'),
  (gen_random_uuid(), 'settings', 'read'),
  (gen_random_uuid(), 'settings', 'write'),
  (gen_random_uuid(), 'suppliers', 'read'),
  (gen_random_uuid(), 'suppliers', 'write'),
  (gen_random_uuid(), 'suppliers', 'delete'),
  (gen_random_uuid(), 'purchase_orders', 'read'),
  (gen_random_uuid(), 'purchase_orders', 'write'),
  (gen_random_uuid(), 'purchase_orders', 'delete'),
  (gen_random_uuid(), 'cargo_shipments', 'read'),
  (gen_random_uuid(), 'cargo_shipments', 'write'),
  (gen_random_uuid(), 'cargo_shipments', 'delete'),
  (gen_random_uuid(), 'walk_in_sales', 'read'),
  (gen_random_uuid(), 'walk_in_sales', 'write'),
  (gen_random_uuid(), 'uzb_stock', 'read'),
  (gen_random_uuid(), 'uzb_stock', 'write'),
  (gen_random_uuid(), 'roles', 'read'),
  (gen_random_uuid(), 'roles', 'write'),
  (gen_random_uuid(), 'users', 'read'),
  (gen_random_uuid(), 'users', 'write'),
  (gen_random_uuid(), 'coupons', 'read'),
  (gen_random_uuid(), 'coupons', 'write'),
  (gen_random_uuid(), 'coupons', 'delete'),
  (gen_random_uuid(), 'expenses', 'read'),
  (gen_random_uuid(), 'expenses', 'write'),
  (gen_random_uuid(), 'telegram', 'read'),
  (gen_random_uuid(), 'telegram', 'write')
ON CONFLICT DO NOTHING;

SELECT COUNT(*) as permissions_seeded
FROM permissions;
